AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # 1. 람다 함수 설정
  RecommendApiFunction: # 함수 이름 (원하는 대로 수정 가능)
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler # 파일명이 app.py라면 그대로 유지
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: inhatc-team2-1-recommend-cache
        - DynamoDBCrudPolicy:
            TableName: inhatc-team2-5-air-cache
      Environment:
        Variables:
          # 실제 AWS 배포 시에는 이 값이 생략되거나 다르게 설정됨
          TABLE_NAME: inhatc-team2-1-recommend-cache
          AIR_TABLE_NAME: inhatc-team2-5-air-cache

  # # 2. 실제 AWS에 생성될 DynamoDB 테이블 정의
  # RecommendCacheTable:
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #     PrimaryKey:
  #       Name: weather_pattern
  #       Type: String
  #     TableName: inhatc-team2-1-recommend-cache

  # aircachetable:
  #     Type: AWS::Serverless::SimpleTable
  #     Properties:
  #       PrimaryKey:
  #         Name: region_code
  #         Type: String
  #       TableName: inhatc-team2-5-air-cache