AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Common S3 & DynamoDB Stack"
Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inhatc-team2-3-frontend
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inhatc-team2-5-raw-data
  ParquetDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inhatc-team2-4-parquet-data