name: Deploy Infrastructure (Full)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "인프라를 정말로 배포하시겠습니까? (yes 입력)"
        required: true
        default: "no"

env:
  # Node.js 20 관련 경고 방지
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::269578498605:role/service-role/github-actions-inhatc-shared
          aws-region: us-east-1

      - name: SAM Build and Deploy
        run: |
          cd infra
          sam build
          # --parameter-overrides 옵션을 통해 GitHub Secrets의 값을 설계도(template.yaml)의 파라미터로 전달합니다.
          sam deploy \
            --stack-name inhatc-team2-infra \
            --region us-east-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --s3-bucket inhatc-team2-5-raw-data \
            --parameter-overrides \
              WeatherApiKey=${{ secrets.WEATHER_API_KEY }} \
              AirApiKey=${{ secrets.AIR_API_KEY }}
