name: Deploy Real-time Pipeline Code

on:
  push:
    branches: [main, develop]
    paths: ["real_time/**"]
  workflow_dispatch:
    inputs:
      confirm:
        description: "수동 배포를 진행하려면 yes를 입력하세요"
        required: true
        type: string
        default: "no"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push' || inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::269578498605:role/service-role/github-actions-inhatc-shared
          aws-region: us-east-1
      - name: Zip and Update Code
        run: |
          cd real_time
          find . -maxdepth 1 -type f | zip ../deploy.zip -@
          aws lambda update-function-code \
            --function-name inhatc-team2-5-real-time-dataAPI \
            --zip-file fileb://../deploy.zip
