name: Deploy Real-time Pipeline Code

on:
  push:
    branches: [main]
    paths: ["real_time/**"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::269578498605:role/service-role/github-actions-inhatc-shared
          aws-region: us-east-1
      - name: Zip and Update Code
        run: |
          cd real_time
          zip -r ../deploy.zip .
          aws lambda update-function-code \
            --function-name inhatc-team2-5-real-time-dataAPI \
            --zip-file fileb://../deploy.zip
