AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DataAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: inhatc-team2-5-dataAPI
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::269578498605:role/SafeRole-inhatc-team2
      Events:
        Hourly:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)"
